[versions]
agp = "8.5.2"
kotlin =                "2.0.20"
coreKtx = "1.15.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
lifecycleRuntimeKtx = "2.8.7"
activityCompose = "1.10.1"
navigationCompose = "2.8.9"
coroutines =                "1.8.0"
lifecycle =                 "2.8.7"
androidx-hilt =             "1.2.0"
hilt =                      "2.51.1"
constraintlayout = "1.0.1"
materialIcons = "1.6.2"
navigationRuntimeKtx =      "2.7.7"
ksp =                   "2.0.20-1.0.25"
compose-bom =               "2025.01.00"
roomCommon = "2.6.1"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }


kotlinx-coroutines-core =       { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android =    { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
lifecycle-livedata =            { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel =           { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-runtime-compose =     { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }
hilt-android =                  { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-android-compiler =         { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-compiler =                 { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-navigation-compose =       { module = "androidx.hilt:hilt-navigation-compose", version.ref = "androidx-hilt" }
compose-material3 =             { group = "androidx.compose.material3", name = "material3" }
compose-ui =                    { group = "androidx.compose.ui", name = "ui" }
compose-ui-tooling-preview =    { group = "androidx.compose.ui", name = "ui-tooling-preview" }
constraintlayout =              { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "constraintlayout" }
compose-material-icons =        { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "materialIcons" }
navigation-runtime-ktx =        { group = "androidx.navigation", name = "navigation-runtime-ktx", version.ref = "navigationRuntimeKtx" }
compose-bom =                   { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-material =              { group = "androidx.compose.material", name = "material" }
androidx-room-common = { group = "androidx.room", name = "room-common", version.ref = "roomCommon" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp =                           { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }

